### ISSUE TITLE
Add express back end 

### ISSUE THREAD

**Issue by mikefab** [unicef/magicbox-kepler-demo#1]
### Why do it?
- On load, kepler should fetch config.json from public dir and load into map.

### References
- https://github.com/unicef/magicbox-maps
- https://medium.freecodecamp.org/how-to-make-create-react-app-work-with-a-node-backend-api-7c5c48acb1b0
- https://github.com/NewGyu/react-tutorial-with-create-react-app

**Comment by thoat** [comment]
WIP on branch [add-express-backend](https://github.com/unicef/kepler-demo/tree/add-express-backend)
